# Generated by Django 4.2.23 on 2026-04-08 08:01

from django.db import migrations, models
import django.db.models.deletion
import pyotp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_no', models.CharField(max_length=11, unique=True, verbose_name='T.C. Kimlik No')),
                ('student_no', models.CharField(max_length=20, unique=True, verbose_name='Öğrenci No')),
                ('first_name', models.CharField(max_length=100, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('faculty', models.CharField(max_length=255, verbose_name='Fakülte')),
                ('department', models.CharField(max_length=255, verbose_name='Bölüm')),
                ('secret_key', models.CharField(default=pyotp.random_base32, max_length=32, verbose_name='TOTP Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='core.student')),
            ],
            options={
                'verbose_name': 'Giriش Logu',
                'verbose_name_plural': 'Giriش Logları',
            },
        ),
    ]
