# Generated by Django 4.2.23 on 2026-04-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_teacher_coursesection_attendancesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Veli Telefon'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Öğrenci Telefon'),
        ),
    ]
