# Generated by Django 4.2.23 on 2026-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_parent_phone_student_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProlizConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='https://obs.avrasya.edu.tr/ProlizMaliRestApi/api/', max_length=255, verbose_name='Proliz API URL')),
                ('username', models.CharField(max_length=100, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(max_length=100, verbose_name='Şifre')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif mi?')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Son Senkronizasyon')),
            ],
            options={
                'verbose_name': 'Proliz API Ayarları',
                'verbose_name_plural': 'Proliz API Ayarları',
            },
        ),
    ]
