# Generated by Django 4.2.23 on 2026-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prolizconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='client_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Öğrenci IP Adresi'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='require_ip_check',
            field=models.BooleanField(default=True, verbose_name='Aynı Ağ / IP Kontrolü Yapılsın mı?'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='teacher_ip',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Öğretmen / Sınıf IP Adresi'),
        ),
    ]
