# Generated by Django 4.2.23 on 2026-07-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendancerecord_client_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='allow_qr_check',
            field=models.BooleanField(default=True, verbose_name='QR Kod ile Yoklamaya İzin Ver'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='require_ip_check',
            field=models.BooleanField(default=True, verbose_name='Wi-Fi IP Otomatik Yoklama'),
        ),
    ]
